; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -S < %s -mtriple=x86_64-unknown-linux-gnu -mcpu=skylake-avx512 | FileCheck %s

; The fsub is modeled as a copyable element of a bundle that is cancelled after
; its ScheduleData dependencies were already cleared. They must be recalculated,
; otherwise the fsub stays unschedulable and the final scheduling deadlocks.

define double @test() {
; CHECK-LABEL: define double @test(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M0:%.*]] = fmul double 0.000000e+00, 0.000000e+00
; CHECK-NEXT:    [[M1:%.*]] = fmul double [[M0]], 0.000000e+00
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x double> poison, double [[M1]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <2 x double> [[TMP0]], <2 x double> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = fadd <2 x double> [[TMP1]], <double +qnan, double 0.000000e+00>
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x double> [[TMP2]], i64 0
; CHECK-NEXT:    [[S0:%.*]] = fsub double 0.000000e+00, [[TMP3]]
; CHECK-NEXT:    [[TMP4:%.*]] = fmul <2 x double> [[TMP2]], zeroinitializer
; CHECK-NEXT:    [[TMP5:%.*]] = fadd <2 x double> zeroinitializer, [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x double> poison, double [[S0]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <2 x double> [[TMP6]], <2 x double> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = fadd <2 x double> [[TMP7]], [[TMP5]]
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <2 x double> [[TMP8]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x double> [[TMP8]], i64 1
; CHECK-NEXT:    [[A6:%.*]] = fadd double [[TMP9]], [[TMP10]]
; CHECK-NEXT:    ret double [[A6]]
;
entry:
  %m0 = fmul double 0.000000e+00, 0.000000e+00
  %m1 = fmul double %m0, 0.000000e+00
  %a0 = fadd double %m1, 0.000000e+00
  %m2 = fmul double %a0, 0.000000e+00
  %d0 = fdiv double 0.000000e+00, 0.000000e+00
  %a1 = fadd double %d0, %m1
  %s0 = fsub double 0.000000e+00, %a1
  %m3 = fmul double %a1, 0.000000e+00
  %a2 = fadd double 0.000000e+00, %m3
  %a3 = fadd double %s0, %a2
  %a4 = fadd double 0.000000e+00, %m2
  %a5 = fadd double %a4, %s0
  %a6 = fadd double %a3, %a5
  ret double %a6
}
